### PR TITLE
Less 3.8

### PR DESCRIPTION
**Pull request by calvinjuarez**
@seanCodes, this PR is 99% of the conversion to Less 3.7.

It's marked "Don't Merge" because there's a discrepancy in how certain `each()` loops execute vs SCSS's `@each`, at the moment (see changes to _bootstrap.css_ in b2837dfab23621bf09193d95c89fb55958711fde).  I'll investigate that when I get a chance to put together a reduced test case and file a bug w/ Less.

I'm opening this PR to claim #7 and because the 3.5+ syntax is exciting!  :P

### CODE REVIEW

**Comment by matthew-dean** [comment]
Ha, shit, @calvinjuarez, why didn't I look for this lol. Looks like I did this for no reason today: https://github.com/seanCodes/bootstrap-less-port/pull/12

**Comment by calvinjuarez** [comment]
@matthew-dean no worries.  I've updated this one with your README and package.json updates, and the unquoting of the `~"calc(...)"` variable values, so now the only difference is the maps, I think.  (And Autoprefixer worked for me.)  :p  I also reviewed #12 so @seanCodes can see what's going on and choose how far from Sass/how into Less he wants this project to go.

**Comment by calvinjuarez** [comment]
Replaced by #13

**Comment by calvinjuarez** [comment]
> 👍 Should I close the other PR?

@matthew-dean Unless you're opposed to #13 for some reason, I think we can simplify by closing #12.  Sorry for the confusion!

**Pull request closed without merging**
